### ISSUE TITLE
delete this

### ISSUE THREAD

**Issue by Mehak-Mehta** [AbeerRao/stock-predictor#1]

**Comment by Mehak-Mehta** [comment]
oh and btw which algorithms should i learn first?

**Comment by AbeerRao** [comment]
First learn data structures.

**Comment by AbeerRao** [comment]
> Hey check [this](https://github.com/Mehak-Mehta/vsinterest). You can download this extension from vscode. Also contributions are welcome!

Its not compatible with M1 Mac latest VS Code version

**Comment by Mehak-Mehta** [comment]
> First learn data structures.

like stack?

**Comment by Mehak-Mehta** [comment]
> > Hey check [this](https://github.com/Mehak-Mehta/vsinterest). You can download this extension from vscode. Also contributions are welcome!
> 
> Its not compatible with M1 Mac latest VS Code version

oof thats bad T-T

**Comment by Mehak-Mehta** [comment]
~not to mention but I gained a follower from stackoverflow~ TwT

**Comment by Mehak-Mehta** [comment]
broooooooooooooooooooooo tfffff
![2021-06-04 (3)](https://user-images.githubusercontent.com/76558546/120787390-eda2fc00-c54c-11eb-930c-95dde376e606.png)

**Comment by Mehak-Mehta** [comment]
> > First learn data structures.
> 
> like stack?

i learned it.... but question still remains where am i going to use this....

**Comment by Mehak-Mehta** [comment]
btw are you in encrypt?? The school one

**Comment by AbeerRao** [comment]
I did it last year. This year IDK when they will have it.

**Comment by AbeerRao** [comment]
> oh and btw which algorithms should i learn first?

Algorithms you can learn any. Just look it up on YT. Or, you can purchase a Udemy course. I have one and its really cool. for only 399 or something.

**Comment by Mehak-Mehta** [comment]
> I did it last year. This year IDK when they will have it.

What did they made you do? And how did you join? Is it like hackathon? Will it help in the future? Does it help in improving your skills?

**Comment by Mehak-Mehta** [comment]
> > oh and btw which algorithms should i learn first?
> 
> Algorithms you can learn any. Just look it up on YT. Or, you can purchase a Udemy course. I have one and its really cool. for only 399 or something.

I started data structures. Ig i will learn Algorithms later

**Comment by Mehak-Mehta** [comment]
Bet i will get the reply at 8am

**Comment by AbeerRao** [comment]
> Bet i will get the reply at 8am
Nope. Its 9. Was getting a haircut.

**Comment by AbeerRao** [comment]
> > > oh and btw which algorithms should i learn first?
> > 
> > 
> > Algorithms you can learn any. Just look it up on YT. Or, you can purchase a Udemy course. I have one and its really cool. for only 399 or something.
> 
> I started data structures. Ig i will learn Algorithms later

Thats also fine

**Comment by Mehak-Mehta** [comment]
> > I did it last year. This year IDK when they will have it.
> 
> What did they made you do? And how did you join? Is it like hackathon? Will it help in the future? Does it help in improving your skills?

?

**Comment by Mehak-Mehta** [comment]
> 
> What did they made you do? And how did you join? Is it like hackathon? Will it help in the future? Does it help in improving your skills?

abeerrrrrrrrr answer this!!!!! T~T

**Comment by Mehak-Mehta** [comment]
delete this issue @AbeerRao

**Comment by Mehak-Mehta** [comment]
`delete this issue` button is on the right hand panel

**Comment by Mehak-Mehta** [comment]
delete this issue as well https://github.com/AbeerRao/AbeerRao/issues/1

**Comment by Mehak-Mehta** [comment]
doesn't look good to have personal chats on github

**Comment by Mehak-Mehta** [comment]
What did they made you do in encrypt?? @AbeerRao

**Comment by Mehak-Mehta** [comment]
delete this dammit @AbeerRao

**Comment by Mehak-Mehta** [comment]
its been 3 weeks you alive????????
